"""
aetherforge init — scaffold a domain pack + first-run command card.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Optional

ROOT = Path(__file__).resolve().parents[2]

TEMPLATE = """# AetherForge domain pack — {domain}
# Generated by: aetherforge init
#
# Train:
#   aetherforge train --recipe {recipe} -c {pack_path} --dry-run
# Live (after connect vast):
#   aetherforge remote launch --exec --recipe {recipe} -c {pack_path}

data:
  domain: {domain}
  description: "{description}"
  topics:
{topics_yaml}
  keywords:
{keywords_yaml}
  actions:
{actions_yaml}
  curated_path: {curated}
  synthetic:
    enabled: true
    num_samples: {num_samples}
    trajectory_hive: true
  quality_gates:
    min_diversity: 0.45
    min_length: 48
  curriculum: true
  privacy_mode: local

training:
  posture: {posture}
  max_steps: {max_steps}

groups:
  enabled: true
  target_num_groups: {num_groups}
  train_scope: {train_scope}
  train_top_n: {train_top_n}
  use_for_training: true

eval:
  scorecard_thresholds:
    domain_score: 0.70
    general_delta_max: -0.06
    high_stakes: {high_stakes}
    require_human_approval: {human_approval}

run:
  name: {run_name}
"""


def _yaml_list(items: list[str], indent: int = 4) -> str:
    sp = " " * indent
    if not items:
        return f"{sp}- general"
    return "\n".join(f"{sp}- {x}" for x in items)


def init_domain(
    domain: str,
    *,
    out_dir: Optional[Path] = None,
    description: str = "",
    topics: Optional[list[str]] = None,
    keywords: Optional[list[str]] = None,
    actions: Optional[list[str]] = None,
    curated_path: Optional[str] = None,
    posture: str = "broad",
    high_stakes: bool = False,
    recipe: str = "broad-flash",
) -> dict[str, Any]:
    domain = (domain or "my_field").strip().lower().replace(" ", "_")
    out_dir = Path(out_dir or (ROOT / "configs" / "domains"))
    out_dir.mkdir(parents=True, exist_ok=True)
    pack_path = out_dir / f"{domain}.yaml"

    topics = topics or [
        f"{domain} core workflows",
        f"{domain} edge cases and failure modes",
        f"{domain} decision criteria and tradeoffs",
    ]
    keywords = keywords or [domain, "decision", "checklist", "risk", "workflow"]
    actions = actions or [
        f"Map the decision tree for a hard {domain} case.",
        f"List red flags that should change the plan in {domain}.",
        f"Explain {domain} tradeoffs to a non-specialist.",
    ]
    posture = (posture or "broad").lower()
    train_scope = "top_n" if posture == "broad" else ("all" if posture == "wide" else "selected")
    train_top_n = 6 if posture == "broad" else 4
    num_groups = 12 if "flash" in recipe else 8
    max_steps = {"specialist": 300, "broad": 1000, "wide": 1500}.get(posture, 500)
    num_samples = {"specialist": 500, "broad": 4000, "wide": 8000}.get(posture, 1000)

    try:
        rel: Path | str = pack_path.relative_to(ROOT)
    except ValueError:
        rel = pack_path

    body = TEMPLATE.format(
        domain=domain,
        description=(description or f"Domain specialist for {domain}").replace('"', "'"),
        topics_yaml=_yaml_list(topics),
        keywords_yaml=_yaml_list(keywords),
        actions_yaml=_yaml_list(actions),
        curated=curated_path or "null",
        num_samples=num_samples,
        posture=posture,
        max_steps=max_steps,
        num_groups=num_groups,
        train_scope=train_scope,
        train_top_n=train_top_n,
        high_stakes="true" if high_stakes else "false",
        human_approval="true" if high_stakes else "false",
        run_name=f"{domain}-{posture}",
        recipe=recipe,
        pack_path=str(rel),
    )
    # fix curated null quoting
    body = body.replace("curated_path: null", "curated_path: null  # set to a jsonl path when ready")
    if curated_path:
        body = body.replace(
            f"curated_path: {curated_path}",
            f'curated_path: "{curated_path}"',
        )

    pack_path.write_text(body, encoding="utf-8")

    dry = f"aetherforge train --recipe {recipe} -c {rel} --dry-run"
    live = f"aetherforge remote launch --exec --recipe {recipe} -c {rel}"
    card = ROOT / "artifacts" / f"INIT-{domain}.md"
    card.parent.mkdir(parents=True, exist_ok=True)
    card.write_text(
        f"""# AetherForge init — `{domain}`

## Pack
`{rel}`

## First dry-run (no GPU)
```bash
{dry}
```

## Sector forensics
```bash
aetherforge forensics --family deepseek_v4_flash --num-groups {num_groups} --markdown
```

## Dashboard
```bash
aetherforge dashboard
# open http://127.0.0.1:8765/ → select the new run → Studio / Forensics
```

## Live on Vast (costs GPU $)
```bash
aetherforge connect vast --host HOST --port PORT
{live}
aetherforge remote pull
```

## Posture
`{posture}` — change in the pack under `training.posture` (specialist|broad|wide).
""",
        encoding="utf-8",
    )

    return {
        "ok": True,
        "domain": domain,
        "pack_path": str(pack_path),
        "card_path": str(card),
        "dry_run_cmd": dry,
        "live_cmd": live,
        "posture": posture,
        "recipe": recipe,
    }
